task: detection

evaluator:
  type: CocoEvaluator
  iou_types: ['bbox', ]

# num_classes: 365
# remap_mscoco_category: False

# num_classes: 91
# remap_mscoco_category: False

num_classes: 2      #80       num_classes should be actual no.of classes + 1 when you set remap_mscoco_category: False
remap_mscoco_category: False    #True


train_dataloader: 
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: /home/fyl/workspace_fyl/dataset/UAVSwarm_COCO/train2017
    ann_file: /home/fyl/workspace_fyl/dataset/UAVSwarm_COCO/annotations/instances_train2017.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  num_workers: 1
  drop_last: True 
  collate_fn:
    type: BatchImageCollateFuncion


val_dataloader:
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: /home/fyl/workspace_fyl/dataset/UAVSwarm_COCO/val2017
    ann_file: /home/fyl/workspace_fyl/dataset/UAVSwarm_COCO/annotations/instances_val2017.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~ 
  shuffle: False
  num_workers: 2
  drop_last: False
  collate_fn:
    type: BatchImageCollateFuncion
